version: '3.8'

services:
  web:
    build: .
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    command: air ./cmd/main.go -b 0.0.0.0

  crdb:
    image: cockroachdb/cockroach:latest
    environment:
      - COCKROACH_USER=${DB_USER}
      - COCKROACH_PASSWORD=${DB_PASSWORD}
      - COCKROACH_NAME=${DB_NAME}
    ports:
      - "26257:26257"
      - "8080:8080"
    command: start-single-node --insecure
    volumes:
      - "./cockroach-data:/cockroach/cockroach-data"